/* Duck TMUA Practice Set B
   Original questions written against the UAT-UK 2026 TMUA specification.
   correct is a zero-based option index. */
const setBRaw=String.raw;
const setBQ=(n,stem,opts,correct,topics,sol)=>({n,stem,opts,correct,topics,sol});

const NEW_SET_B_P1=[
setBQ(1,
  setBRaw`A polynomial \(P(x)\) leaves remainder \(3x+1\) when divided by \(x^2-1\). What is the remainder when \(P(x^2)\) is divided by \(x^2-1\)?`,
  [setBRaw`\(1\)`,setBRaw`\(2\)`,setBRaw`\(3\)`,setBRaw`\(4\)`],3,['General algebra'],
  setBRaw`<b>Answer D.</b> Let the required remainder be \(R(x)=ax+b\). At both roots \(x=1\) and \(x=-1\) of the divisor, \(R(x)=P(x^2)=P(1)\). Hence \(R(1)=R(-1)\), so \(a=0\) and the remainder is the constant \(P(1)\). The original remainder gives \(P(1)=3(1)+1=4\).`),
setBQ(2,
  setBRaw`The side length of a square is measured as \(8.0\text{ cm}\), correct to the nearest \(0.1\text{ cm}\). If its area is \(A\text{ cm}^2\), which statement is correct?`,
  [setBRaw`\(63.20<A<64.80\)`,setBRaw`\(63.2025\le A<64.8025\)`,setBRaw`\(63.2025<A\le64.8025\)`,setBRaw`\(63.6\le A<64.4\)`,setBRaw`\(64.0\le A<64.8025\)`,setBRaw`\(63.2025\le A\le64.8025\)`],1,['Geometry','General algebra'],
  setBRaw`<b>Answer B.</b> Rounding to the nearest \(0.1\) gives \(7.95\le s<8.05\). Since \(s\) is positive, squaring preserves the order: \(7.95^2\le A<8.05^2\). These squares are \(63.2025\) and \(64.8025\).`),
setBQ(3,
  setBRaw`Points \(O,A,B\) have coordinates \((0,0),(6,0),(0,9)\), respectively. Point \(P\) lies on \(OA\) with \(OP:PA=1:2\), and point \(Q\) lies on \(OB\) with \(OQ:QB=2:1\). Lines \(AQ\) and \(BP\) intersect at \(R\). What is the \(y\)-coordinate of \(R\)?`,
  [setBRaw`\(\frac92\)`,setBRaw`\(\frac{24}{5}\)`,setBRaw`\(5\)`,setBRaw`\(\frac{36}{7}\)`,setBRaw`\(6\)`,setBRaw`\(\frac{45}{7}\)`,setBRaw`\(7\)`],3,['Geometry','General algebra'],
  setBRaw`<b>Answer D.</b> The ratio conditions give \(P=(2,0)\) and \(Q=(0,6)\). Line \(AQ\), through \((6,0)\) and \((0,6)\), has equation \(y=6-x\). Line \(BP\), through \((0,9)\) and \((2,0)\), has equation \(y=9-\tfrac92x\). Equating the two expressions gives \(x=6/7\), and hence \(y=6-6/7=36/7\).`),
setBQ(4,
  setBRaw`A data set takes the values \(1,2,3,4\) with frequencies \(a,3,2,1\), respectively. Its mean is \(2.25\). If one item is selected at random from the data set, what is the probability that its value is below the mean?`,
  [setBRaw`\(\frac58\)`,setBRaw`\(\frac12\)`,setBRaw`\(\frac35\)`,setBRaw`\(\frac23\)`],0,['Probability and Statistics','General algebra'],
  setBRaw`<b>Answer A.</b> The total frequency is \(a+6\), while the sum of the values is \(a+6+6+4=a+16\). Thus \((a+16)/(a+6)=9/4\), giving \(4a+64=9a+54\), so \(a=2\). Five of the eight items have value \(1\) or \(2\), both below \(2.25\), so the probability is \(5/8\).`),
setBQ(5,
  setBRaw`How many integer values of \(x\) satisfy
  \[|x^2-5x+4|\le2?\]`,
  [setBRaw`\(2\)`,setBRaw`\(3\)`,setBRaw`\(4\)`,setBRaw`\(5\)`,setBRaw`\(6\)`,setBRaw`\(7\)`],2,['General algebra','Functions and Graphs'],
  setBRaw`<b>Answer C.</b> The inequality is equivalent to \(-2\le x^2-5x+4\le2\). The first part gives \((x-2)(x-3)\ge0\), so \(x\le2\) or \(x\ge3\). The second gives \(x^2-5x+2\le0\), whose roots lie between \(0,1\) and between \(4,5\). The integer values in the intersection are \(1,2,3,4\), giving four values.`),
setBQ(6,
  setBRaw`A quantity \(y\) is directly proportional to \(x^2\) and inversely proportional to \(\sqrt z\), where all quantities are positive. If \(x\) is doubled and \(z\) is multiplied by \(9\), by what factor is \(y\) multiplied?`,
  [setBRaw`\(\frac23\)`,setBRaw`\(1\)`,setBRaw`\(\frac43\)`,setBRaw`\(2\)`],2,['General algebra'],
  setBRaw`<b>Answer C.</b> We may write \(y=kx^2/\sqrt z\). Doubling \(x\) multiplies the numerator by \(4\), while multiplying \(z\) by \(9\) multiplies \(\sqrt z\) by \(3\). The overall factor is therefore \(4/3\).`),
setBQ(7,
  setBRaw`Solve
  \[\log_2(x-1)+\log_2(x+3)=3.\]`,
  [setBRaw`\(-1+2\sqrt3\)`,setBRaw`\(1+2\sqrt3\)`,setBRaw`\(-1+\sqrt{12}\) and \(-1-\sqrt{12}\)`,setBRaw`\(3\)`,setBRaw`\(5\)`],0,['Exponentials and Logarithms','General algebra'],
  setBRaw`<b>Answer A.</b> Both logarithms require \(x>1\). Combining them gives \(\log_2((x-1)(x+3))=3\), so \((x-1)(x+3)=8\). Hence \(x^2+2x-11=0\), giving \(x=-1\pm2\sqrt3\). Only \(-1+2\sqrt3\) satisfies \(x>1\).`),
setBQ(8,
  setBRaw`In triangle \(ABC\), \(AB=8\), \(AC=6\) and \(\angle B=30^\circ\). There are two possible values of \(\angle C\). What is the product of the corresponding values of \(\cos C\)?`,
  [setBRaw`\(-\frac23\)`,setBRaw`\(-\frac59\)`,setBRaw`\(-\frac49\)`,setBRaw`\(\frac49\)`,setBRaw`\(\frac59\)`,setBRaw`\(-\frac19\)`],1,['Geometry','Trigonometry'],
  setBRaw`<b>Answer B.</b> By the sine rule, \(\sin C/8=\sin30^\circ/6\), so \(\sin C=2/3\). The two possible angles are supplementary, so their cosines are opposites. Since \(\cos^2C=1-\sin^2C=5/9\), their product is \(-5/9\).`),
setBQ(9,
  setBRaw`The trapezium rule with four equal strips is used to estimate
  \[\int_0^2x^4\,dx.\]
  What is the estimate minus the exact value?`,
  [setBRaw`\(\frac{13}{80}\)`,setBRaw`\(\frac{21}{80}\)`,setBRaw`\(\frac{37}{80}\)`,setBRaw`\(\frac{49}{80}\)`,setBRaw`\(\frac{53}{80}\)`,setBRaw`\(\frac{69}{80}\)`],4,['Integration'],
  setBRaw`<b>Answer E.</b> The strip width is \(1/2\), and the ordinates are \(0,1/16,1,81/16,16\). The estimate is
  \[\frac12\left(\frac{0+16}{2}+\frac1{16}+1+\frac{81}{16}\right)=\frac{113}{16}.\]
  The exact integral is \([x^5/5]_0^2=32/5\). Their difference is \(113/16-32/5=(565-512)/80=53/80\).`),
setBQ(10,
  setBRaw`A circle has centre \(O\). The tangent at a point \(C\) meets the line \(OB\), extended beyond \(B\), at \(T\), where \(B\) is on the circle. If \(\angle CTO=20^\circ\), what is the angle subtended by chord \(BC\) at the circumference on the opposite arc?`,
  [setBRaw`\(20^\circ\)`,setBRaw`\(25^\circ\)`,setBRaw`\(30^\circ\)`,setBRaw`\(35^\circ\)`,setBRaw`\(40^\circ\)`],3,['Geometry'],
  setBRaw`<b>Answer D.</b> A radius is perpendicular to the tangent, so \(\angle OCT=90^\circ\). In triangle \(OCT\), \(\angle COT=70^\circ\). Since \(O,B,T\) are collinear in that order, \(\angle COB=70^\circ\). An angle at the circumference subtended by the same chord is half the angle at the centre, so it is \(35^\circ\).`),
setBQ(11,
  setBRaw`Real numbers \(x\) and \(y\) satisfy \(x+y=7\) and \(x^2+y^2=29\). What is \(x^3+y^3\)?`,
  [setBRaw`\(91\)`,setBRaw`\(119\)`,setBRaw`\(133\)`,setBRaw`\(147\)`,setBRaw`\(203\)`],2,['General algebra'],
  setBRaw`<b>Answer C.</b> From \((x+y)^2=x^2+y^2+2xy\), we get \(49=29+2xy\), so \(xy=10\). Then
  \[x^3+y^3=(x+y)^3-3xy(x+y)=7^3-3(10)(7)=343-210=133.\]`),
setBQ(12,
  setBRaw`For all real \(x\), define
  \[F(x)=\int_0^x(t^2-5t+6)\,dt.\]
  On which values of \(x\) is \(F\) strictly increasing?`,
  [setBRaw`Only when \(x<2\)`,setBRaw`Only when \(2<x<3\)`,setBRaw`Only when \(x>3\)`,setBRaw`When \(x<3\)`,setBRaw`When \(x<2\) or \(x>3\)`],4,['Integration','Functions and Graphs'],
  setBRaw`<b>Answer E.</b> By the Fundamental Theorem of Calculus, \(F'(x)=x^2-5x+6=(x-2)(x-3)\). This is positive outside its two roots and negative between them. Therefore \(F\) is strictly increasing when \(x<2\) or \(x>3\).`),
setBQ(13,
  setBRaw`Tangents to the curve \(y=x^3-3x\) are drawn at the points where they are parallel to the line \(y=9x\). What is the distance between the points where these two tangents meet the \(y\)-axis?`,
  [setBRaw`\(16\)`,setBRaw`\(32\)`,setBRaw`\(36\)`,setBRaw`\(40\)`,setBRaw`\(64\)`,setBRaw`\(72\)`],1,['Differentiation','Geometry'],
  setBRaw`<b>Answer B.</b> The gradient is \(3x^2-3\). Setting this equal to \(9\) gives \(x=\pm2\). At \(x=2\), \(y=2\), so the tangent is \(y-2=9(x-2)\), with intercept \(-16\). At \(x=-2\), \(y=-2\), giving intercept \(16\). Their separation is \(32\).`),
setBQ(14,
  setBRaw`The line \(y=mx+6\), where \(m<0\), and the coordinate axes enclose a triangle of area \(12\). What is \(m\)?`,
  [setBRaw`\(-\frac32\)`,setBRaw`\(-\frac43\)`,setBRaw`\(-1\)`,setBRaw`\(-\frac34\)`],0,['Geometry','General algebra'],
  setBRaw`<b>Answer A.</b> The \(y\)-intercept is \(6\), and the positive \(x\)-intercept is \(-6/m\). Thus the area is \(\tfrac12(6)(-6/m)=-18/m\). Setting this equal to \(12\) gives \(m=-3/2\).`),
setBQ(15,
  setBRaw`Solve
  \[\sqrt{x+6}-\sqrt x=1.\]`,
  [setBRaw`\(\frac94\)`,setBRaw`\(4\)`,setBRaw`\(\frac{25}{4}\)`,setBRaw`\(9\)`,setBRaw`\(\frac{49}{4}\)`],2,['General algebra'],
  setBRaw`<b>Answer C.</b> Rearranging gives \(\sqrt{x+6}=\sqrt x+1\). Squaring yields \(x+6=x+2\sqrt x+1\), so \(\sqrt x=5/2\) and \(x=25/4\). Substitution confirms that it satisfies the original equation.`),
setBQ(16,
  setBRaw`The five letters A, A, B, B, C are placed in a random order, with each distinct ordering equally likely. What is the probability that the first and last letters are the same?`,
  [setBRaw`\(\frac15\)`,setBRaw`\(\frac3{10}\)`,setBRaw`\(\frac13\)`,setBRaw`\(\frac25\)`,setBRaw`\(\frac12\)`,setBRaw`\(\frac23\)`],0,['Combinatorics','Probability and Statistics'],
  setBRaw`<b>Answer A.</b> There are \(5!/(2!2!)=30\) distinct arrangements. If both end letters are A, the three middle letters are B, B, C, giving \(3!/2!=3\) arrangements. Similarly, using B at both ends gives another \(3\) arrangements. No ordering can have C at both ends because there is only one C. Hence there are \(6\) favourable arrangements and the probability is \(6/30=1/5\).`),
setBQ(17,
  setBRaw`A function \(f\) is odd, meaning that \(f(-x)=-f(x)\) for every real \(x\). It is given that
  \[\int_{-1}^{2}f(x)\,dx=3,\qquad \int_{2}^{5}f(x)\,dx=-4.\]
  Find \(\displaystyle\int_{-5}^{1}f(x)\,dx\).`,
  [setBRaw`\(-7\)`,setBRaw`\(1\)`,setBRaw`\(3\)`,setBRaw`\(4\)`,setBRaw`\(7\)`],1,['Integration','Functions and Graphs'],
  setBRaw`<b>Answer B.</b> Oddness gives \(\int_{-b}^{-a}f(x)\,dx=-\int_a^b f(x)\,dx\). Hence \(\int_{-5}^{-2}f=4\). It also gives \(\int_{-2}^{1}f=-\int_{-1}^{2}f=-3\). Adding the contiguous intervals gives \(4-3=1\).`),
setBQ(18,
  setBRaw`For real \(a\), let
  \[f(x)=x^3-3ax^2+3x.\]
  For which values of \(a\) does the graph of \(y=f(x)\) have two distinct stationary points?`,
  [setBRaw`\(|a|<1\)`,setBRaw`\(|a|\le1\)`,setBRaw`\(|a|=1\)`,setBRaw`\(|a|>1\)`,setBRaw`All real \(a\)`],3,['Differentiation','Functions and Graphs','General algebra'],
  setBRaw`<b>Answer D.</b> Stationary points satisfy \(f'(x)=3(x^2-2ax+1)=0\). This quadratic has two distinct real roots exactly when its discriminant is positive: \(4a^2-4>0\). Thus \(a^2>1\), or \(|a|>1\).`),
setBQ(19,
  setBRaw`The line \(y=mx+6\) cuts the circle \(x^2+y^2=25\) in a chord of length \(6\). There are two possible values of \(m\). What is their product?`,
  [setBRaw`\(-\frac54\)`,setBRaw`\(-1\)`,setBRaw`\(-\frac45\)`,setBRaw`\(\frac45\)`,setBRaw`\(\frac54\)`],0,['Geometry','General algebra'],
  setBRaw`<b>Answer A.</b> Half the chord has length \(3\), so the perpendicular distance from the centre to the line is \(\sqrt{5^2-3^2}=4\). Writing the line as \(mx-y+6=0\), this distance is \(6/\sqrt{m^2+1}\). Hence \(6/\sqrt{m^2+1}=4\), so \(m^2=5/4\). The two slopes are opposites, and their product is \(-5/4\).`),
setBQ(20,
  setBRaw`A right-angled triangle has perpendicular sides of lengths \(x\) and \(12-x\), where \(0<x<12\). It is rotated through a full turn about the side of length \(x\), forming a cone. You may use
  \[\text{volume of a cone}=\frac13\pi r^2h.\]
  What is the greatest possible volume?`,
  [setBRaw`\(64\pi\)`,setBRaw`\(72\pi\)`,setBRaw`\(81\pi\)`,setBRaw`\(96\pi\)`,setBRaw`\(\frac{256\pi}{3}\)`],4,['Differentiation','Geometry'],
  setBRaw`<b>Answer E.</b> The height is \(x\) and the radius is \(12-x\), so \(V=(\pi/3)x(12-x)^2\). Apart from the positive constant \(\pi/3\), the derivative is \((12-x)(12-3x)\). The interior stationary point is \(x=4\), and the endpoint volumes tend to zero, so this gives the maximum. Thus \(V=(\pi/3)(4)(8^2)=256\pi/3\).`)
];

const NEW_SET_B_P2=[
setBQ(1,
  setBRaw`Suppose that the statements “if \(P\) is true, then \(Q\) is true” and “if \(Q\) is true, then \(R\) is true” are both true. Which statement must be true?`,
  ['If \(P\) is true, then \(R\) is true.','If \(R\) is true, then \(P\) is true.','If \(P\) is false, then \(R\) is false.','If \(R\) is false, then \(Q\) is true.'],0,['Logic'],
  setBRaw`<b>Answer A.</b> If \(P\) is true, the first implication makes \(Q\) true; the second then makes \(R\) true. This is a chain of implications. None of the reverse implications is guaranteed.`),
setBQ(2,
  setBRaw`Consider the statement:<blockquote>If the graph of \(y=f(x)\) has no \(x\)-intercepts, then \(f(x)>0\) for every real \(x\).</blockquote>Which is its contrapositive?`,
  ['If the graph has an \(x\)-intercept, then \(f(x)\le0\) for every real \(x\).','If \(f(x)>0\) for every real \(x\), then the graph has no \(x\)-intercepts.','If \(f(x)\le0\) for at least one real \(x\), then the graph has an \(x\)-intercept.','If \(f(x)<0\) for every real \(x\), then the graph has no \(x\)-intercepts.'],2,['Logic','Functions and Graphs'],
  setBRaw`<b>Answer C.</b> The contrapositive of “if A then B” is “if not B then not A”. Here, not B means that \(f(x)\le0\) for at least one real \(x\), while not A means that the graph has at least one \(x\)-intercept.`),
setBQ(3,
  setBRaw`A student claims that, for positive real numbers \(a,b,c,d\), if \(a+b>c+d\) and \(ab>cd\), then both \(a>c\) and \(b>d\). Which choice is a counterexample?`,
  [setBRaw`\((a,b,c,d)=(5,4,3,2)\)`,setBRaw`\((6,2,5,1)\)`,setBRaw`\((3,5,2,4)\)`,setBRaw`\((4,4,5,2)\)`,setBRaw`\((7,3,6,4)\)`],3,['Logic','General algebra'],
  setBRaw`<b>Answer D.</b> For \((4,4,5,2)\), the hypotheses hold because \(4+4>5+2\) and \(4\cdot4>5\cdot2\). However, the conclusion fails because \(a=4\) is not greater than \(c=5\). One counterexample disproves a universal claim.`),
setBQ(4,
  setBRaw`To prove that there is no smallest positive rational number, a student assumes that \(r\) is the smallest one. They observe that \(r/2\) is also positive and rational, but \(r/2<r\). Which method of proof is being used?`,
  ['Direct deduction','Proof by contradiction','Proof by cases','Disproof by counterexample'],1,['Logic','General algebra'],
  setBRaw`<b>Answer B.</b> The proof begins by assuming the opposite of the desired conclusion: that a smallest positive rational number exists. It then derives a contradiction by producing a smaller one. This is proof by contradiction.`),
setBQ(5,
  setBRaw`In this question, “or” is inclusive, so either or both conditions may hold. How many integers \(x\) with \(-5\le x\le5\) satisfy
  \[(x<1\text{ or }x\ge3)\text{ and not }(x<0)?\]`,
  [setBRaw`\(2\)`,setBRaw`\(3\)`,setBRaw`\(4\)`,setBRaw`\(5\)`,setBRaw`\(6\)`,setBRaw`\(7\)`,setBRaw`\(8\)`],2,['Logic','General algebra'],
  setBRaw`<b>Answer C.</b> The final condition gives \(x\ge0\). Combining this with \(x<1\) or \(x\ge3\) leaves \(x=0\), or \(x=3,4,5\). There are four integers.`),
setBQ(6,
  setBRaw`A proof that \(n(n+1)\) is even for every integer \(n\) considers separately the cases where \(n\) is even and where \(n\) is odd. Which observation completes both cases?`,
  ['If \(n\) is even then \(n\) is a factor of the product; if \(n\) is odd then \(n+1\) is even.','The sum of two consecutive integers is odd.','Every integer has an even factor.','The product of two odd integers is even.','If a product is even, both its factors are even.'],0,['Logic','Number Theory'],
  setBRaw`<b>Answer A.</b> If \(n\) is even, the product has the even factor \(n\). If \(n\) is odd, the consecutive integer \(n+1\) is even, so the product again has an even factor. The two cases exhaust all integers.`),
setBQ(7,
  setBRaw`Six real numbers have mean \(12\). Which argument correctly proves that at least one of them is at least \(12\) and at least one is at most \(12\)?`,
  ['The numbers cannot all be equal.','The largest and smallest numbers must add to \(24\).','Exactly three numbers are at least \(12\).','The range must contain \(12\) as one of the data values.','If all were below \(12\), their sum would be below \(72\); if all were above \(12\), their sum would be above \(72\).'],4,['Logic','Probability and Statistics'],
  setBRaw`<b>Answer E.</b> A mean of \(12\) means that the sum is \(72\). If every number were below \(12\), the sum would be below \(72\), and if every number were above \(12\), the sum would be above \(72\). Therefore neither possibility can occur.`),
setBQ(8,
  setBRaw`Which statement is true?`,
  ['For every real \(x\), there is a real \(y\) such that \(x+y=xy\).','For every real \(x\ne1\), there is exactly one real \(y\) such that \(x+y=xy\).','There is a real \(y\) such that \(x+y=xy\) for every real \(x\).','For every real \(y\), there are two real values of \(x\) such that \(x+y=xy\).','There are no real \(x,y\) satisfying \(x+y=xy\).','There is exactly one ordered pair \((x,y)\) satisfying \(x+y=xy\).'],1,['Logic','General algebra'],
  setBRaw`<b>Answer B.</b> Rearranging gives \(y(x-1)=x\). If \(x\ne1\), there is exactly one solution, \(y=x/(x-1)\). If \(x=1\), the equation becomes \(1+y=y\), which is impossible, so option A fails and B is correct.`),
setBQ(9,
  setBRaw`A study finds a strong positive correlation between time spent on practice questions and test score. Which conclusion is justified by this information alone?`,
  ['Increasing practice time will necessarily increase every student’s score.','Practice time is the only factor affecting score.','High scores cause students to spend more time practising.','In this study, higher practice time tended to be associated with higher score, but causation has not been established.','The same correlation must occur in every group of students.'],3,['Logic','Probability and Statistics'],
  setBRaw`<b>Answer D.</b> Correlation describes an observed association. It does not by itself establish the direction of causation, exclude other factors, or prove that the same pattern holds for every student or population.`),
setBQ(10,
  setBRaw`Functions \(f\) and \(g\) are strictly increasing for all real inputs. Which statement must be true?`,
  ['The function \(f(x)+g(x)\) is strictly increasing.','The function \(f(x)-g(x)\) is strictly increasing.','The function \(f(x)g(x)\) is strictly increasing.','The function \(f(g(x))\) is strictly decreasing.','\(f(g(x))=g(f(x))\) for every real \(x\).'],0,['Logic','Functions and Graphs'],
  setBRaw`<b>Answer A.</b> If \(x_1<x_2\), then \(f(x_1)<f(x_2)\) and \(g(x_1)<g(x_2)\). Adding gives \(f(x_1)+g(x_1)<f(x_2)+g(x_2)\). The other claims can fail; for example, differences and products need not preserve strict increase.`),
setBQ(11,
  setBRaw`Ten distinct real numbers are placed in increasing order. Their median is \(12\). Which statement must be true?`,
  ['One of the numbers is \(12\).','Their mean is \(12\).','Exactly five numbers are below \(12\) and exactly five are above \(12\).','The fifth number is \(11\) and the sixth is \(13\).','Their range is greater than \(24\).','Their sum is \(120\).'],2,['Logic','Probability and Statistics'],
  setBRaw`<b>Answer C.</b> For ten ordered values, the median is the mean of the fifth and sixth. Because the values are distinct, the fifth is strictly less than the sixth. If their mean is \(12\), the fifth is below \(12\) and the sixth is above \(12\). Hence the first five are below and the last five are above.`),
setBQ(12,
  setBRaw`A sequence \(u_1,u_2,\ldots\) is strictly increasing, meaning that \(u_{n+1}>u_n\) for every positive integer \(n\). Which statement need not be true?`,
  ['\(u_{20}>u_{10}\)','No two terms are equal.','Some term is positive.','\(u_n>u_1\) for every \(n>1\).','Every difference \(u_{n+1}-u_n\) is positive.'],2,['Logic','Sequences and Series'],
  setBRaw`<b>Answer C.</b> The sequence \(u_n=-1/n\) is strictly increasing because its terms approach zero from below, but no term is positive. Each of the other statements follows directly by repeatedly using \(u_{n+1}>u_n\).`),
setBQ(13,
  setBRaw`In a group of \(80\) students, \(46\) study Mathematics and \(39\) study Physics. What is the least number who must study both subjects?`,
  [setBRaw`\(0\)`,setBRaw`\(5\)`,setBRaw`\(7\)`,setBRaw`\(39\)`,setBRaw`\(41\)`,setBRaw`\(46\)`],1,['Logic','Combinatorics'],
  setBRaw`<b>Answer B.</b> Counting the two subject groups gives \(46+39=85\) places. There are only \(80\) students, so at least five places must be double-counted. This minimum is attainable, so at least \(5\) students study both.`),
setBQ(14,
  setBRaw`The non-vertical lines \(y=mx+1\) and \(y=nx-3\) are perpendicular, and \(m>0\). Which statement must be true?`,
  [setBRaw`\(n=m\)`,setBRaw`\(n=1/m\)`,setBRaw`\(n>0\)`,setBRaw`\(n=-1/m<0\)`,setBRaw`\(mn=1\)`],3,['Logic','Geometry'],
  setBRaw`<b>Answer D.</b> Perpendicular non-vertical lines have gradients whose product is \(-1\). Thus \(mn=-1\), so \(n=-1/m\). Since \(m>0\), this also shows \(n<0\).`),
setBQ(15,
  setBRaw`Consider the true statement:<blockquote>If \(x>y\), then \(2^x>2^y\).</blockquote>Which is its converse?`,
  ['If \(x\le y\), then \(2^x\le2^y\).','If \(2^x\le2^y\), then \(x\le y\).','If \(2^x>2^y\), then \(x>y\).','If \(x<y\), then \(2^x<2^y\).','If \(2^x=2^y\), then \(x=y\).'],2,['Logic','Exponentials and Logarithms'],
  setBRaw`<b>Answer C.</b> The converse of “if A then B” is “if B then A”. Interchanging the hypothesis and conclusion gives: if \(2^x>2^y\), then \(x>y\).`),
setBQ(16,
  setBRaw`Which identity gives a complete direct proof that \(x+1/x\ge2\) for every positive real \(x\)?`,
  [setBRaw`\(x+\frac1x-2=(x-1)(1-\frac1x)\)`,setBRaw`\(x+\frac1x=\frac{x^2+1}{x}\)`,setBRaw`\(x^2+1\ge0\)`,setBRaw`\(x+\frac1x-2=\frac{(x-1)^2}{x}\ge0\)`,setBRaw`\((x+\frac1x)^2=x^2+2+\frac1{x^2}\)`],3,['Logic','General algebra'],
  setBRaw`<b>Answer D.</b> Because \(x>0\), the denominator is positive, and \((x-1)^2\ge0\). Therefore \((x-1)^2/x\ge0\). The identity shows directly that this is exactly \(x+1/x-2\), proving the required inequality.`),
setBQ(17,
  setBRaw`A function \(f\) is defined for every real number. Which condition is necessary and sufficient for \(f\) not to be constant?`,
  ['For every real \(u,v\), \(f(u)\ne f(v)\).','There exist real \(u,v\) such that \(f(u)\ne f(v)\).','There exists a real \(u\) such that \(f(u)=0\).','For every real \(u\), \(f(u)>u\).','There exist real \(u,v\) such that \(u\ne v\) and \(f(u)=f(v)\).'],1,['Logic','Functions and Graphs'],
  setBRaw`<b>Answer B.</b> A constant function takes the same value at every pair of inputs. Therefore it is non-constant exactly when at least one pair of inputs gives different outputs. This establishes both necessity and sufficiency.`),
setBQ(18,
  setBRaw`A shop increases a price by \(20\%\) and then decreases the new price by \(20\%\). A student says the two changes cancel. What is the flaw in this reasoning?`,
  ['The decrease is calculated from a different, larger price than the increase.','Percentages cannot be used for prices.','A percentage decrease always exceeds the corresponding increase.','The order of the changes is irrelevant because the final price is \(20\%\) higher.','There is no flaw; the original price is restored.'],0,['Logic','General algebra'],
  setBRaw`<b>Answer A.</b> If the original price is \(P\), the new price is \(1.2P\), and the decrease produces \(0.8(1.2P)=0.96P\). The two percentages use different base quantities, so they do not cancel; the final price is \(4\%\) lower.`),
setBQ(19,
  setBRaw`Two fair coins are tossed. Let event H be “the first coin shows heads” and event E be “exactly one coin shows heads”. Two events are called independent if knowing that one occurred does not change the probability of the other. Which statement is correct?`,
  ['H and E are not independent because both mention heads.','H and E are independent: the probability of E is \(1/2\), and it is still \(1/2\) when H is known to have occurred.','H and E are independent because they cannot occur together.','H and E are not independent because the probability of both occurring is \(1/2\).','There is insufficient information to decide.'],1,['Logic','Probability and Statistics'],
  setBRaw`<b>Answer B.</b> The four equally likely outcomes are HH, HT, TH and TT. Event E occurs in HT and TH, so its probability is \(1/2\). If H is known, only HH and HT remain, and E occurs in one of these two outcomes, again with probability \(1/2\). Thus the events are independent under the definition given.`),
setBQ(20,
  setBRaw`Exactly one of the statements \(P,Q,R\) is false. In addition, both “\(P\) only if \(Q\)” and “\(R\) if \(Q\)” are true. Which row gives the truth values of \(P,Q,R\), respectively?`,
  ['true, true, false','false, true, true','true, false, true','true, false, false','false, false, true','false, true, false','false, false, false','true, true, true'],1,['Logic'],
  setBRaw`<b>Answer B.</b> “\(P\) only if \(Q\)” means that \(P\) true forces \(Q\) true. “\(R\) if \(Q\)” means that \(Q\) true forces \(R\) true. If \(Q\) were false, then because exactly one statement is false, \(P\) would be true, contradicting the first implication. If \(R\) were false, then \(P,Q\) would be true, contradicting the second. Therefore \(P\) is the sole false statement, while \(Q,R\) are true.`)
];
