/* Set B, substantive revision 3. Ratings are editorial estimates, not measured ability. */
const BR=String.raw;
const BM=['I only','II only','III only','I and II only','I and III only','II and III only','I, II and III','None of them'];
const BQ=(n,stem,choices,key,topics,rating,method,solution)=>({n,stem,opts:choices.split(' || '),correct:'ABCDEFGHIJ'.indexOf(key),topics:topics.split(' / '),estimatedDifficulty:rating,method,sol:`<b>Answer ${key}.</b> ${solution}`});
const BS=(n,stem,key,topics,rating,method,solution)=>BQ(n,stem+' Which statements must be true?',BM.join(' || '),key,topics,rating,method,solution);
const REVISED_SET_B_P1=[
BQ(1,BR`A polynomial \(P\) leaves remainder \(2x+1\) when divided by \((x-1)(x-2)\). A second polynomial is defined by \(Q(x)=P(3-x)+xP(x)\). What remainder does \(Q\) leave on division by the same quadratic?`,BR`\(5x+3\) || \(3x+5\) || \(5x-3\) || \(7x+1\) || \(2x^2+x+5\)`,'A','General algebra',5.5,'Evaluate at divisor roots, then reconstruct the linear remainder.',BR`The given remainder implies \(P(1)=3\) and \(P(2)=5\), regardless of the other coefficients. Hence \(Q(1)=5+3=8\) and \(Q(2)=3+2(5)=13\). The required remainder has degree less than two, so write it as \(ax+b\). Then \(a+b=8\) and \(2a+b=13\), yielding \(a=5,b=3\). The quadratic option has the right values at the roots but is not an admissible remainder because its degree is two.`),
BQ(2,BR`A machine produces \(5\) components on its first day. On each subsequent day it produces three fewer than twice the previous day's output. After \(n\) days, the total output is \(16\) more than twice the output on day \(n\). What is \(n\)?`,BR`\(7\) || \(8\) || \(9\) || \(10\) || \(16\) || \(24\)`,'B','Sequences and Series / General algebra',6,'Sum an affine recurrence without explicitly solving it.',BR`Write the daily outputs as \(a_1,\ldots,a_n\) and their sum as \(S\). Adding \(a_{j+1}=2a_j-3\) from \(j=1\) to \(n-1\) gives \(S-5=2(S-a_n)-3(n-1)\). Rearranging, \(S=2a_n+3n-8\). The stated condition therefore gives \(3n-8=16\), so \(n=8\). As a check, subtracting the fixed value 3 from each daily output gives the geometric sequence 2,4,8,...; day eight produces 259 and the first eight days total 534, which is \(2(259)+16\).`),
BQ(3,BR`The coefficients of \((1+2x)^6\), in ascending powers of \(x\), are \(c_0,c_1,\ldots,c_6\). Without expanding every term, find \[c_0+\frac{c_2}{4}+\frac{c_4}{16}+\frac{c_6}{64}.\]`,BR`\(1\) || \(6\) || \(16\) || \(31\) || \(32\) || \(64\)`,'E','Sequences and Series / General algebra',6,'Extract a weighted parity sum by evaluating at opposite inputs.',BR`Let \(F(x)=(1+2x)^6\). The required expression is the sum of the even-power terms of \(F(1/2)\). Adding \(F(1/2)\) to \(F(-1/2)\) cancels all the odd-power terms and doubles the even ones. Thus the answer is \(\tfrac12(2^6+0^6)=32\). Omitting the constant term gives 31; omitting the division by two gives 64. This is a sum of coefficients, not a request to find one coefficient.`),
BQ(4,BR`Start with the graph \(y=(x-1)^2-4\). To make graph G, first translate it three units to the right, then compress it parallel to the \(x\)-axis with scale factor \(1/2\). To make graph H, apply the same two transformations in the opposite order. What is the \(x\)-coordinate of their intersection?`,BR`\(\frac54\) || \(\frac74\) || \(\frac94\) || \(\frac52\) || \(\frac{11}{4}\) || \(\frac72\)`,'E','Functions and Graphs / General algebra',5.5,'Track transformations of vertices in a noncommuting pair.',BR`The original vertex is \((1,-4)\). For G it moves first to \((4,-4)\), then to \((2,-4)\). For H it moves first to \((1/2,-4)\), then to \((7/2,-4)\). Both final graphs have the same quadratic coefficient, 4, and the same minimum value. They intersect halfway between their vertex abscissae: \((2+7/2)/2=11/4\). Equivalently solve \((2x-4)^2=(2x-7)^2\).`),
BQ(5,BR`A bag contains three red counters and two blue counters. Counters are drawn without replacement until both colours have appeared. You are told that the process stopped on the third draw. What is the probability that the first counter was red?`,BR`\(\frac13\) || \(\frac25\) || \(\frac12\) || \(\frac35\) || \(\frac23\) || \(\frac34\)`,'E','Probability and Statistics',6,'Condition on a stopping event rather than on the final colour alone.',BR`Stopping on draw three means the first two colours matched and the third differed. The only possible colour sequences are RRB and BBR. Their probabilities are \((3/5)(2/4)(2/3)=1/5\) and \((2/5)(1/4)(3/3)=1/10\). Therefore the required probability is \((1/5)/(1/5+1/10)=2/3\). RBR and BRB do not qualify: the process would already have stopped on draw two.`),
BQ(6,BR`An angle \(x\) lies between \(0\) and \(\pi\), and \(\sin x\cos x=-3/8\). There are two possible values of \(\tan x\). What is the positive difference between them?`,BR`\(\frac{\sqrt7}{3}\) || \(\frac{2\sqrt7}{3}\) || \(\frac43\) || \(\frac83\) || \(\frac{4\sqrt7}{3}\)`,'B','Trigonometry / General algebra',6,'Convert a trig product to an equation for the tangent and retain both solutions.',BR`Here \(\cos x\ne0\). Put \(t=\tan x\). Using \(1+\tan^2x=1/\cos^2x\), derived from \(\sin^2x+\cos^2x=1\), gives \(\sin x\cos x=t/(1+t^2)\). Thus \(3t^2+8t+3=0\) and \(t=(-4\pm\sqrt7)/3\). Both values are negative and correspond to angles in the second quadrant, so neither is discarded. Their positive difference is \(2\sqrt7/3\).`),
BQ(7,BR`A positive number \(x\) satisfies \[\log_2(\log_2 x)+\log_2\!\left(\log_2\frac{16}{x}\right)>1.\] Which describes all possible values of \(x\)?`,BR`\(1<x<16\) || \(2<x<8\) || \(2-\sqrt2<x<2+\sqrt2\) || \(2^{2-\sqrt2}<x<2^{2+\sqrt2}\) || \(x<2^{2-\sqrt2}\) or \(x>2^{2+\sqrt2}\) || \(2^{2-\sqrt2}\le x\le2^{2+\sqrt2}\)`,'D','Exponentials and Logarithms / General algebra',6.5,'Check nested domains, then solve a transformed quadratic inequality.',BR`Set \(u=\log_2x\). The inner arguments of the outer logarithms must both be positive, giving \(0<u<4\). The inequality becomes \(\log_2(u(4-u))>1\), hence \(u(4-u)>2\). Completing the square gives \((u-2)^2<2\), so \(2-\sqrt2<u<2+\sqrt2\). This interval already lies inside \((0,4)\). Since powers of 2 preserve order, the answer follows, with strict endpoints.`),
BQ(8,BR`In triangle ABC, \(AB=8\), \(AC=6\) and \(\angle BAC=60^\circ\). Point P is the midpoint of AB, and Q lies on AC with \(AQ=2QC\). The segments BQ and CP meet at R. What is the area of triangle RQC?`,BR`\(\frac{\sqrt3}{2}\) || \(\sqrt3\) || \(2\sqrt3\) || \(3\sqrt3\) || \(4\sqrt3\) || \(6\sqrt3\)`,'B','Geometry / Trigonometry / General algebra',6.5,'Find an interior intersection before scaling areas by a shared base.',BR`Choose \(A=(0,0)\), \(B=(8,0)\), \(C=(3,3\sqrt3)\). Then \(P=(4,0)\) and \(Q=(2,2\sqrt3)\). A point on BQ has coordinates \((8-6t,2\sqrt3\,t)\), where \(0\le t\le1\); a point on CP has coordinates \((3+s,3\sqrt3(1-s))\). At their intersection \(8-6t=3+s\) and \(2t=3(1-s)\), which give \(t=3/4\). Thus \(RQ= BQ/4\). Triangles RQC and BQC have a common base QC, and R's perpendicular distance to AC is one quarter of B's. Also QC is one third of AC, so the required area is \(1/12\) of ABC. Since ABC has area \(\tfrac12(8)(6)\sin60^\circ=12\sqrt3\), the answer is \(\sqrt3\).`),
BQ(9,BR`A quadratic function is non-negative on \([0,2]\). Applying the trapezium rule over this interval gives 14 with one strip and 12 with two equal strips. What is its exact integral over \([0,2]\)?`,BR`\(\frac{32}3\) || \(\frac{34}3\) || \(\frac{35}3\) || \(12\) || \(\frac{38}3\) || \(14\)`,'B','Integration / General algebra',6.5,'Recover an exact quadratic integral from two approximations.',BR`Write \(f(x)=ax^2+bx+c\). The one-strip estimate is \(4a+2b+2c=14\); the two-strip estimate is \(3a+2b+2c=12\). Subtraction gives \(a=2\), so \(2b+2c=6\). Integrating gives \(8a/3+2b+2c=16/3+6=34/3\). The linear and constant contributions are integrated exactly by both trapezium estimates; the differing curvature contribution is what determines the correction.`),
BQ(10,BR`The circles \(x^2+y^2=25\) and \((x-6)^2+y^2=25\) meet at A and B. The tangents to the first circle at A and B meet at T. If O is the origin, what is the area of quadrilateral OATB?`,BR`\(\frac{32}3\) || \(\frac{50}3\) || \(\frac{64}3\) || \(\frac{80}3\) || \(\frac{100}3\) || \(\frac{125}3\)`,'E','Geometry / General algebra',6.5,'Combine a common chord, tangent equations and diagonals.',BR`Subtracting the circle equations gives \(x=3\), so take \(A=(3,4)\), \(B=(3,-4)\). Perpendicularity to OA gives the tangent \(3x+4y=25\); similarly the other is \(3x-4y=25\). Therefore \(T=(25/3,0)\). The perpendicular diagonals OT and AB have lengths \(25/3\) and 8. Splitting into triangles, their enclosed quadrilateral has area \(\tfrac12(25/3)(8)=100/3\).`),
BQ(11,BR`Two cyclists each use the same two positive speeds, \(u>v\). The first spends half the journey time at each speed. The second travels half the journey distance at each speed. The first cyclist's average speed is \(9/8\) of the second's. Find \(u/v\).`,BR`\(2\) || \(\frac94\) || \(\frac52\) || \(3\) || \(4\)`,'A','General algebra',6,'Distinguish equal-time and equal-distance averages before solving a ratio equation.',BR`The first average is \((u+v)/2\). If the second travels distance d, their time is \(d/(2u)+d/(2v)\), so their average is \(2uv/(u+v)\). The ratio condition gives \((u+v)^2/(4uv)=9/8\). With \(r=u/v\), this becomes \(2r^2-5r+2=0\), whose roots are 2 and \(1/2\). The stipulated \(u>v\) selects 2. A ratio of arithmetic means alone misses the different weighting.`),
BQ(12,BR`A cubic curve has equation \(y=x^3+ax^2+bx+c\). Rotating its graph through \(180^\circ\) about \((2,5)\) leaves the graph unchanged. Its tangent at the point with \(x=1\) has gradient \(-3\). What is the \(y\)-coordinate of its local minimum?`,BR`\(5-2\sqrt2\) || \(5+2\sqrt2\) || \(5+4\sqrt2\) || \(2-4\sqrt2\) || \(3-4\sqrt2\) || \(5-4\sqrt2\)`,'F','Differentiation / Functions and Graphs / General algebra',6.5,'Translate rotational symmetry into coefficient constraints, then identify the lower turning point.',BR`Put \(u=x-2\) and \(v=y-5\). After this translation the cubic has form \(v=u^3+pu^2+qu+r\). Half-turn symmetry means that replacing \(u\) by \(-u\) replaces \(v\) by \(-v\); comparing coefficients forces \(p=r=0\). Therefore \(y=(x-2)^3+q(x-2)+5\). At \(x=1\) its derivative is \(3+q=-3\), so \(q=-6\). Stationary points satisfy \(3u^2-6=0\), giving \(u=\pm\sqrt2\). The derivative changes from negative to positive at \(u=\sqrt2\), identifying the local minimum. Its ordinate is \(5+(\sqrt2)^3-6\sqrt2=5-4\sqrt2\). The other stationary point gives the plus-sign distractor.`),
BQ(13,BR`A curve has equation \(y=x^3-3x\). At two distinct points its tangents are parallel. Their intersections with the \(y\)-axis are 32 units apart. What is the common gradient of the tangents?`,BR`\(3\) || \(6\) || \(9\) || \(12\) || \(15\) || \(21\)`,'C','Differentiation / Geometry',6,'Work backwards from tangent intercepts to the contact points.',BR`At abscissa t, the derivative is \(3t^2-3\), and the tangent intercept is \((t^3-3t)-t(3t^2-3)=-2t^3\). Distinct points with equal derivatives have abscissae t and -t, with \(t>0\). Their intercept separation is therefore \(4t^3=32\). Hence \(t=2\) and the common gradient is \(3(2^2)-3=9\). Using the difference of the curve ordinates instead of the tangent intercepts would answer a different question.`),
BQ(14,BR`A sequence has sum of its first \(n\) terms \[S_n=\frac{n^2}{n+1},\qquad n\ge1.\] What is the least positive integer \(n\) for which its \(n\)th term is greater than \(99/100\)?`,BR`\(8\) || \(9\) || \(10\) || \(11\) || \(99\) || \(100\)`,'C','Sequences and Series / General algebra',6.5,'Recover a term from partial sums before applying a strict threshold.',BR`Polynomial division gives \(S_n=n-1+1/(n+1)\). For \(n\ge2\), \(a_n=S_n-S_{n-1}=1-1/(n(n+1))\). The same formula gives \(a_1=1/2\), agreeing with \(S_1\). Thus the condition is \(n(n+1)>100\). At 9 the product is 90; at 10 it is 110, and the product increases for positive n. The least n is therefore 10. Solving the inequality for the partial sum instead of the term gives an incorrect threshold.`),
BQ(15,BR`Points A and B have coordinates \((4,1)\) and \((1,4)\). A path travels along straight segments from A to P, then to Q, then to B, where P lies on the positive \(x\)-axis and Q on the positive \(y\)-axis. What is the least possible total length?`,BR`\(3\sqrt2\) || \(2\sqrt{17}\) || \(5\sqrt2\) || \(8\) || \(2\sqrt{26}\)`,'C','Geometry',7,'Unfold two reflections and check that the minimising path respects the axis order.',BR`Reflect B in the y-axis to \((-1,4)\), then reflect this point in the x-axis to \((-1,-4)\). Reflect Q in the x-axis to Q'. Reflections preserve distance, so the path length becomes AP+PQ'+Q'B'', at least the straight distance from \((4,1)\) to \((-1,-4)\), namely \(5\sqrt2\). This bound is attainable: that straight line crosses the x-axis at \((3,0)\) and the negative y-axis at \((0,-3)\), giving the allowed original points \(P=(3,0),Q=(0,3)\).`),
BQ(16,BR`Eight positions, labelled 1 to 8, lie around a circle; positions 8 and 1 are adjacent. Three positions are chosen uniformly from all possible three-position selections. What is the probability that no two chosen positions are adjacent?`,BR`\(\frac27\) || \(\frac5{14}\) || \(\frac37\) || \(\frac12\) || \(\frac47\) || \(\frac67\)`,'A','Combinatorics / Probability and Statistics',7,'Count circular gaps with the correct multiplicity.',BR`There are \(\binom83=56\) selections. In a valid selection the three clockwise gaps of unchosen positions between chosen ones are positive integers with sum 5. Subtracting one from each, the possible triples have forms (2,0,0) or (1,1,0), giving 3+3=6 ordered triples. Choosing a starting labelled position gives \(8\cdot6\) descriptions, but each selection is counted three times, once for each chosen starting point. Hence there are 16 valid selections and the probability is \(16/56=2/7\).`),
BQ(17,BR`An integrable function \(f\) is odd: \(f(-x)=-f(x)\). It is known that \[\int_{-1}^{2}f(x)\,dx=3,\qquad\int_2^5f(x)\,dx=-4.\] A second graph is obtained by moving the graph of f two units to the right and three units upwards. What is the integral of this second function from -3 to 3?`,BR`\(11\) || \(15\) || \(17\) || \(19\) || \(21\) || \(25\)`,'D','Integration / Functions and Graphs',7,'Combine a graph translation, cancellation by oddness and interval bookkeeping.',BR`The second function is \(g(x)=f(x-2)+3\). Its integral is 18 plus the integral of f from -5 to 1, by translating the horizontal interval. Oddness gives \(\int_{-5}^{-2}f=4\) and \(\int_{-2}^{1}f=-\int_{-1}^{2}f=-3\). Their sum is 1, so the answer is 19. The vertical translation contributes \(3\times6\), not just 3; the horizontal translation changes the endpoints rather than the height.`),
BQ(18,BR`For a positive parameter k, consider \[|x-1|+|x-4|=kx.\] Which condition on k is necessary and sufficient for there to be exactly one distinct real solution?`,BR`\(k\ge2\) || \(k>2\) || \(k=\frac34\) or \(k\ge2\) || \(\frac34\le k<2\) || \(\frac34<k\le2\) || \(k=\frac34\) or \(k>3\)`,'C','Functions and Graphs / General algebra',7.5,'Count intersections across three linear branches and deduplicate corner solutions.',BR`The left side equals \(5-2x\) for \(x\le1\), 3 for \(1\le x\le4\), and \(2x-5\) for \(x\ge4\). The candidate roots are \(5/(k+2)\), valid for \(k\ge3\); \(3/k\), valid for \(3/4\le k\le3\); and \(5/(2-k)\), valid for \(3/4\le k<2\). At \(k=3/4\), the last two coincide at x=4. For \(3/4<k<2\) there are two roots. For \(k\ge2\) there is one, with the first two coinciding at x=1 when k=3. Below \(3/4\) there are none.`),
BQ(19,BR`For each real c, the line \(y=x+c\) meets the curve \(y=(x+1)/(x-1)\) in two distinct points. What is the least possible distance between those two points, as c varies?`,BR`\(2\sqrt2\) || \(\sqrt{10}\) || \(4\) || \(3\sqrt2\) || \(2\sqrt5\)`,'C','Functions and Graphs / Geometry / General algebra',7.5,'Relate the discriminant to root separation and then to geometric distance.',BR`Multiplying by x-1 gives \(x^2+(c-2)x-(c+1)=0\), with discriminant \(c^2+8>0\). The excluded value x=1 never satisfies this quadratic (substitution gives -2), so both roots are genuine. Their horizontal separation is \(\sqrt{c^2+8}\). The line has slope 1, so the vertical separation has the same magnitude, making the distance \(\sqrt{2(c^2+8)}\). This is minimised at c=0, where the distance is 4.`),
BQ(20,BR`A horizontal line \(y=k\) cuts the curve \(y=(x^2-4x)^2\) at four distinct points. Their \(x\)-coordinates, in increasing order, form an arithmetic progression. Find k.`,BR`\(\frac{16}5\) || \(\frac{64}9\) || \(9\) || \(\frac{256}{25}\) || \(12\) || \(\frac{144}{9}\)`,'D','Functions and Graphs / Sequences and Series / General algebra',7.5,'Use symmetry and equal spacing to determine the height of a four-point section.',BR`Put \(u=x-2\), so the curve is \((u^2-4)^2\). Four distinct intersections require \(0<k<16\), and their shifted coordinates are \(-a,-b,b,a\), where \(a=\sqrt{4+\sqrt k}\), \(b=\sqrt{4-\sqrt k}>0\). Equal spacing means \(a-b=2b\), hence \(a=3b\). Squaring gives \(4+\sqrt k=9(4-\sqrt k)\), so \(\sqrt k=16/5\) and \(k=256/25\). This lies in the required interval; the four coordinates are distinct.`)
];
const REVISED_SET_B_P2=[
BS(1,BR`Let x and y be positive real numbers.
<p>I. If \(x+y>2\), then \(x>1\) or \(y>1\) (or both).</p>
<p>II. If \(xy>1\), then \(x+y>2\).</p>
<p>III. If \(x+y>2\), then \(xy>1\).</p>`,'D','Logic / General algebra',5.5,'Separate a true implication from its converse using a boundary counterexample.',BR`I is true: if both numbers were at most 1, their sum would be at most 2. For II, \((x-y)^2\ge0\) gives \((x+y)^2\ge4xy>4\); positivity of the sum then gives \(x+y>2\). III is false: take x=3 and y=1/4, so the sum exceeds 2 but the product is only 3/4. The square identity proves II without assuming any additional inequality theorem.`),
BQ(2,BR`Consider the statement: "If every term of a real sequence is positive, then every partial sum is positive." A partial sum means the sum of the first n terms for some positive integer n. Which statement is its contrapositive?`,BR`If some term is non-positive, some partial sum is non-positive. || If every partial sum is positive, every term is positive. || If some partial sum is non-positive, some term is non-positive. || If every partial sum is non-positive, every term is non-positive. || If some partial sum is negative, every term is negative. || If no term is positive, no partial sum is positive.`,'C','Logic / Sequences and Series',5.5,'Negate two universal statements without strengthening either negation.',BR`The contrapositive of "if A then B" is "if not B then not A". Not every partial sum being positive means at least one partial sum is non-positive, including zero. Likewise, not every term being positive means at least one term is non-positive. Option C states exactly these negations in the required order. A reverses the implication, B is the converse, and the remaining options incorrectly replace "some" with "every" or remove the zero case.`),
BQ(3,BR`A proposed comparison rule says: for positive numbers a,b,c,d, if \(a+b>c+d\) and \(ab>cd\), then both \(a>c\) and \(b>d\). Which ordered quadruple \((a,b,c,d)\) disproves the rule?`,BR`\((5,4,3,2)\) || \((6,2,5,1)\) || \((3,5,2,4)\) || \((4,4,5,2)\) || \((7,3,6,4)\)`,'D','Logic / General algebra',5,'Check all hypotheses before rejecting a universal comparison claim.',BR`For D, the sum comparison is 8>7 and the product comparison is 16>10, but a>c is false because 4<5. A, B and C satisfy the conclusion, so do not disprove anything. E fails the strict sum hypothesis: both sums are 10; its product hypothesis also fails, with 21<24. A candidate with a false conclusion is not a counterexample unless all the hypotheses hold.`),
BQ(4,BR`A student solves \(|x-2|<x+1\) as follows.
<p>Line 1. Any solution has \(x+1>0\).</p>
<p>Line 2. Squaring the original inequality gives \((x-2)^2<(x+1)^2\).</p>
<p>Line 3. Expansion and simplification give \(x>1/2\).</p>
<p>Line 4. For every \(x>1/2\), the right side of the original inequality is positive.</p>
<p>Line 5. Consequently, reversing the squaring step is valid and the solution is \(x>1/2\).</p>
Which line contains the first error?`,BR`Line 1 || Line 2 || Line 3 || Line 4 || Line 5 || There is no error.`,'F','Logic / General algebra',6,'Audit an equivalence including the sign condition that makes squaring reversible.',BR`There is no error. A non-negative absolute value cannot be strictly less than a non-positive number, proving line 1. Squaring positive sides preserves a strict inequality. Expansion gives \(-6x+3<0\), hence x>1/2. This implies x+1>0, so taking non-negative square roots reverses the squared inequality. Lines 4 and 5 check sufficiency; without that check, squaring alone would only supply a necessary condition.`),
BQ(5,BR`Let \(0<a<b\), and set \(h=2ab/(a+b)\). The following steps are intended to prove \(a<h<b\).
<p>P. Multiplying \(a<b\) by a and by b gives \(a^2<ab<b^2\).</p>
<p>Q. Since \(a+b>0\), divide the last double inequality by a+b.</p>
<p>R. Hence \(a<2ab/(a+b)<b\).</p>
<p>S. Adding ab to the two outer comparisons gives \(a(a+b)<2ab<b(a+b)\).</p>
Which order gives a valid proof as written?`,BR`P, Q, S, R || P, S, Q, R || S, P, Q, R || P, S, R, Q || Q, P, S, R`,'B','Logic / General algebra',5.5,'Track the double inequality and the exact point at which a positive division is justified.',BR`P obtains the two comparisons using positivity of a and b. Adding ab produces the factored inequality in S. Q divides that inequality by its positive common factor a+b, and R states the result. Thus the order is P,S,Q,R. The wording "the last double inequality" matters: placing Q immediately after P would divide \(a^2<ab<b^2\), which does not yield the displayed conclusion in R.`),
BS(6,BR`A function f is non-decreasing, meaning that \(f(u)\le f(v)\) whenever \(u<v\). It is integrable on \([0,1]\), and \(f(0)=f(1)=7\).
<p>I. \(f(x)=7\) for every \(0\le x\le1\).</p>
<p>II. \(f(x)=7\) for every real x.</p>
<p>III. \(\int_0^1 f(x)\,dx=7\).</p>`,'E','Logic / Functions and Graphs / Integration',5.5,'Use an order squeeze locally without extending it outside the known interval.',BR`For 0<x<1, monotonicity gives \(7=f(0)\le f(x)\le f(1)=7\), proving I. III follows by integrating this constant over an interval of length one. II need not hold: the function equal to 7 up to x=1 and equal to x+6 after x=1 is non-decreasing, has the required endpoint values, but is not globally constant. Equality at two inputs controls the interval between them, not the whole domain.`),
BS(7,BR`A cubic polynomial f has positive leading coefficient and three distinct real roots \(a<b<c\).
<p>I. \(f'(a)>0\).</p>
<p>II. \(f'(b)<0\).</p>
<p>III. \(f'(x)>0\) for every \(x>c\).</p>`,'G','Logic / Differentiation / General algebra',7,'Translate root ordering into local derivative signs and an exterior expansion.',BR`Write \(f(x)=A(x-a)(x-b)(x-c)\) with A>0. Expanding about a, the coefficient of x-a is \(A(a-b)(a-c)>0\), so I holds. Expanding about b similarly gives \(f'(b)=A(b-a)(b-c)<0\). For III put x=c+t with t>0. Then \(f(c+t)=A[t^3+(2c-a-b)t^2+(c-a)(c-b)t]\). Differentiation of this polynomial gives a sum of positive terms for t>0. All three statements follow using only differentiation of powers.`),
BQ(8,BR`A fraction is in its lowest terms when its numerator and denominator have no common integer factor greater than 1. For a positive integer n, the fraction \(n/(n+1)\) is written as a terminating decimal if it can be expressed as \(m/10^r\) for integers m and \(r\ge0\). How many integers \(n\) with \(1\le n\le19\) give a terminating decimal?`,BR`\(5\) || \(6\) || \(7\) || \(8\) || \(9\) || \(10\)`,'C','Logic / Number Theory',6.5,'Derive a denominator criterion from the supplied definition rather than assume it.',BR`Consecutive integers have no common factor greater than 1, so the fraction is already reduced. For its denominator to divide a power of 10, its only prime factors can be 2 and 5. Conversely every denominator of that form divides a sufficiently large power of 10. Among 2,...,20 these denominators are 2,4,5,8,10,16,20. There are seven, corresponding to n=1,3,4,7,9,15,19. Including denominator 1 would incorrectly count n=0.`),
BQ(9,BR`Exactly one of three boxes A, B and C contains a gold counter, exactly one contains a silver counter, and one is empty. The labels read:
<p>On A: "The gold counter is in B."</p>
<p>On B: "The silver counter is in C."</p>
<p>On C: "A is empty."</p>
Exactly two labels are true. Which box contains the gold counter?`,BR`A || B || C || Either A or B, but it is not determined which. || Either B or C, but it is not determined which. || The conditions are inconsistent.`,'F','Logic',6.5,'Enumerate coupled possibilities rather than treating truth assignments as independent.',BR`If the label on A is true, gold is in B. The remaining contents of A and C are silver and empty. If C holds silver then A is empty, so all three labels are true; if C is empty then A holds silver, so only the first label is true. Thus exactly two true labels is impossible in this case. If the label on A is false, the other two must both be true: silver is in C and A is empty. Gold would then be in B, making the first label true after all. No arrangement satisfies the conditions.`),
BQ(10,BR`A student claims that every polynomial f with \(f(0)=f(1)=0\) has \(\int_0^1f(x)\,dx\le0\). The proposed proof is:
<p>Line 1. The Factor Theorem gives \(f(x)=x(x-1)g(x)\) for a polynomial g.</p>
<p>Line 2. For \(0\le x\le1\), \(x\ge0\) and \(x-1\le0\).</p>
<p>Line 3. Therefore \(x(x-1)\le0\) on that interval.</p>
<p>Line 4. It follows that \(f(x)\le0\) throughout the interval.</p>
<p>Line 5. Integrating gives the desired conclusion.</p>
Where is the first error?`,BR`Line 1 || Line 2 || Line 3 || Line 4 || Line 5 || There is no error.`,'D','Logic / Integration / General algebra',6,'Identify a missing sign assumption rather than object to a valid factorisation.',BR`Line 4 ignores the sign of g. The preceding lines are valid, including for the zero polynomial by taking g=0. But g might be negative: for example choose g=-1. Then \(f(x)=x(1-x)\) satisfies both endpoint conditions, is positive inside the interval, and has integral \(1/2-1/3=1/6>0\). Line 5 would follow if line 4 were true; the first invalid inference is therefore line 4, not the integration.`),
BS(11,BR`For each real parameter t, define \(f_t(x)=(x-t)^2-1\).
<p>I. For every real t, there exists a real x with \(f_t(x)<0\).</p>
<p>II. There exists a real x such that \(f_t(x)<0\) for every real t.</p>
<p>III. For every real x, there exists a real t with \(f_t(x)<0\).</p>`,'E','Logic / Functions and Graphs',6,'Distinguish a parameter-dependent choice from a single universal witness.',BR`I holds by choosing x=t, giving -1. III holds by choosing t=x for the same reason. II is false: once any x has been fixed, choose t=x+2, giving \(f_t(x)=3>0\). The witnesses in I and III may depend on the universally quantified quantity. In II, x must be chosen before t and must work for every t; that stronger requirement fails.`),
BQ(12,BR`For positive a,b with a+b=1, a proof is to show \[\frac{a}{1+b}+\frac{b}{1+a}\ge\frac23.\]
<p>P. From \((a-b)^2\ge0\), deduce \(p\le1/4\).</p>
<p>Q. Put p=ab, so \(a^2+b^2=1-2p\) and \((1+a)(1+b)=2+p>0\).</p>
<p>R. Combining the fractions gives \((2-2p)/(2+p)\).</p>
<p>S. Subtracting 2/3 from this expression gives \((2-8p)/(3(2+p))\).</p>
<p>T. The numerator is non-negative and the denominator positive, proving the claim.</p>
Which order is a valid proof as written?`,BR`P, Q, R, S, T || Q, P, S, R, T || Q, R, S, T, P || Q, P, R, S, T || Q, S, P, R, T || R, Q, P, S, T`,'D','Logic / General algebra',7,'Track a substitution, rational identity and sign argument through a proof.',BR`Q defines p and supplies the identities and positive denominator. P follows because \((a-b)^2=(a+b)^2-4ab=1-4p\ge0\). R then combines the original fractions, and S subtracts the proposed lower bound. Finally T uses P and Q to conclude non-negativity. In option A, p is used before its definition; in B and E, S refers to an expression not yet obtained; in C the bound required by T has not yet been proved; in F the substitution has not yet been introduced.`),
BQ(13,BR`Five distinct non-negative integers have mean 4 and median 4. A student says that their largest value cannot exceed 10. Which option correctly assesses the claim?`,BR`False: 11 is attainable. || False: 12 is attainable. || True, but 10 is not attainable. || True, and 10 is attainable. || False: there is no upper bound.`,'D','Logic / Probability and Statistics',6,'Use ordering and non-negativity to prove and attain a sharp statistical bound.',BR`In increasing order write the values as a,b,4,d,e. Their sum is 20. Distinct non-negative integers force \(a\ge0\), \(b\ge1\) and \(d\ge5\), so \(e=20-a-b-4-d\le10\). The values 0,1,4,5,10 achieve equality and have both the required mean and median. Thus the bound is not just necessary; it is attainable. Omitting either distinctness or non-negativity changes the optimisation problem.`),
BQ(14,BR`Let f be a polynomial. Condition P is that \(f'(x)>0\) for every real x. Condition Q is that \(f(u)<f(v)\) whenever \(u<v\). Which statement is correct?`,BR`P is sufficient but not necessary for Q. || P is necessary but not sufficient for Q. || P is both necessary and sufficient for Q. || P is neither necessary nor sufficient for Q.`,'A','Logic / Differentiation',5,'Distinguish a sufficient derivative test from the order definition.',BR`An everywhere-positive derivative guarantees strict increase, so P is sufficient for Q. It is not necessary: \(f(x)=x^3\) is strictly increasing on the real line, but \(f'(0)=0\). To check the order claim directly, for u<v, \(v^3-u^3=(v-u)(v^2+uv+u^2)>0\); the second factor is positive unless u=v=0, which is excluded. This question concerns a single connected domain, avoiding any ambiguity about combining separate intervals.`),
BS(15,BR`A fair six-sided die is rolled. Event A is that the result is 1, 2 or 3. Event B is that it is even. Event C is that it is 1, 2, 4 or 5. Events E and F are called independent when the probability that both occur equals the product of their individual probabilities.
<p>I. A and B are independent.</p>
<p>II. A and C are independent.</p>
<p>III. B and C are independent.</p>`,'F','Logic / Probability and Statistics',6.5,'Apply the definition to all three pairs; overlapping events can still be independent.',BR`The individual probabilities are 1/2,1/2,2/3. A and B overlap only at 2, giving 1/6, not \((1/2)(1/2)=1/4\); I fails. A and C overlap at 1 and 2, giving 1/3, which equals \((1/2)(2/3)\). B and C overlap at 2 and 4, also giving 1/3. Thus II and III hold. Neither sharing outcomes nor being described using the same die decides independence without this calculation.`),
BS(16,BR`For x>0, a proposed bound is \[\left|x-\frac1x\right|\le c\left(x+\frac1x\right).\]
<p>I. The bound holds for every x>0 when c=1.</p>
<p>II. There is some constant c<1 for which it holds for every x>0.</p>
<p>III. When c=1, equality holds for at least one x>0.</p>`,'A','Logic / General algebra',7,'Separate validity, optimality and attainment of an inequality bound.',BR`Both x and 1/x are positive, so their absolute difference is strictly less than their sum. Thus I holds and III fails. To disprove II, negative c already fails at x=1. For \(0\le c<1\), choose \(x>1\) with \(x^2>(1+c)/(1-c)\). Then \((1-c)x^2>1+c\), equivalent to \(x-1/x>c(x+1/x)\), violating the bound. Consequently 1 is the least possible constant even though equality is never attained.`),
BS(17,BR`A sequence is defined by \(a_1=0\) and \(a_{n+1}=3-a_n/2\).
<p>I. Every even-indexed term is greater than 2.</p>
<p>II. Every term lies in the interval \([0,3]\).</p>
<p>III. \(|a_{n+1}-2|=|a_n-2|/2\) for every positive integer n.</p>`,'G','Logic / Sequences and Series',6.5,'Use a fixed-point shift to establish alternating signs and contraction.',BR`Subtracting 2 gives \(a_{n+1}-2=-(a_n-2)/2\). Therefore \(a_n-2=-2(-1/2)^{n-1}\). Its sign is positive exactly for even n, proving I, and its magnitude halves at each step, proving III. The odd terms start at 0 and lie below 2; the even terms start at 3 and lie above 2 with successively smaller deviations. All terms consequently lie in [0,3], proving II. Alternation does not prevent convergence.`),
BS(18,BR`Let \(f(x)=2x+1\) and \(g(x)=ax+b\), where a,b are real constants. Suppose \(f(g(x))=g(f(x))\) for every real x.
<p>I. \(g(-1)=-1\).</p>
<p>II. g is strictly increasing.</p>
<p>III. \(f(f(g(x)))=g(f(f(x)))\) for every real x.</p>`,'E','Logic / Functions and Graphs / General algebra',6.5,'Derive the affine compatibility condition and propagate it through composition.',BR`Expanding the given relation gives \(2ax+2b+1=2ax+a+b\), so b=a-1. Hence \(g(-1)=-a+b=-1\), proving I. Taking a=-1,b=-2 meets the condition but makes g decreasing, disproving II. For III, apply the original relation first at x and then at f(x): \(f(f(g(x)))=f(g(f(x)))=g(f(f(x)))\). The statement uses composition, not multiplication of function values.`),
BQ(19,BR`Let \(a<b\) be real numbers. For a real \(x\), consider the condition \[|x-a|+|x-b|=|2x-a-b|.\] Which condition on \(x\) is necessary and sufficient?`,BR`\(a\le x\le b\) || \(a<x<b\) || \(x\le a\) or \(x\ge b\) || \(x<a\) or \(x>b\) || \(x=(a+b)/2\) || \(x=a\) or \(x=b\)`,'C','Logic / General algebra / Functions and Graphs',6.5,'Characterise equality by signs and treat the endpoints explicitly.',BR`Put u=x-a and v=x-b, so the equation is \(|u|+|v|=|u+v|\). If both have the same sign, or one is zero, equality holds. If they have opposite nonzero signs, \(|u+v|\) is the difference of their magnitudes and is strictly less than their sum. Since \(a<b\), opposite signs occur exactly when \(a<x<b\). Equality therefore holds on the two exterior regions, including x=a and x=b. This also proves necessity, not only sufficiency.`),
BS(20,BR`For a real constant k, define \(P(n)=n^2+kn+1\). A perfect square here means the square of an integer, including 0. Each proposed test below is considered on its own.
<p>I. If P(0) and P(1) are perfect squares, then P(n) is a perfect square for every integer n.</p>
<p>II. If P(-1) and P(1) are perfect squares, then P(n) is a perfect square for every integer n.</p>
<p>III. If P(1) and P(2) are perfect squares, then P(n) is a perfect square for every integer n.</p>`,'B','Logic / Number Theory / General algebra',7.5,'Distinguish a forcing pair of tests from convincing but insufficient finite evidence.',BR`I fails at k=7: P(0)=1 and P(1)=9 are squares, but P(2)=19 is not. For II, P(-1)=2-k and P(1)=2+k are non-negative integer squares whose sum is 4. The only possible pairs are (0,4) and (4,0), forcing k=2 or -2. Then \(P(n)=(n+1)^2\) or \((n-1)^2\), proving the conclusion for every integer n. III fails at k=142: P(1)=144 and P(2)=289 are squares, but P(3)=436 lies strictly between \(20^2=400\) and \(21^2=441\).`)
];
